### ISSUE TITLE
Running 10 moodle backup jobs parallel results in different exceptions

### ISSUE THREAD

**Issue by ghost** [backmeup/backmeup-prototype#69]
Following errors occurred during the run of 10 parallel backup jobs (in sum 200 Jobs).

You might reproduce this by running the script "python-tests/ParallelJobMoodleZip.py" in your backmeup setup.

```
java.io.FileNotFoundException: http://gtn02.gtn-solutions.com/moodle20/blocks/backmeup/portfoliofile.php/bmu/temp/exportdata/backmeup_2012_10_30_16_07/Game%20Based%20Learning/Aufteilung%20der%20Begriffe%20f%C3%BCr%20das%20Glossar.html
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1401)
        at java.net.URL.openStream(URL.java:1029)
        at org.backmeup.moodle.MoodleDatasource.getFile(MoodleDatasource.java:40)
        at org.backmeup.plugin.api.connectors.FilesystemLikeDatasource.download(FilesystemLikeDatasource.java:38)
        at org.backmeup.plugin.api.connectors.FilesystemLikeDatasource.downloadAll(FilesystemLikeDatasource.java:24)
        at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:228)
        at $Proxy98.downloadAll(Unknown Source)
        at org.backmeup.job.impl.BackupJobRunner.executeBackup(BackupJobRunner.java:187)
        at org.backmeup.job.impl.rabbitmq.RabbitMQJobReceiver$1.run(RabbitMQJobReceiver.java:141)
        at java.lang.Thread.run(Thread.java:679)
```

Visiting the website resulted in following error page:

```
Debug info: error() is a deprecated function, please call print_error() instead of error()
Stack trace:
line 836 of /lib/deprecatedlib.php: moodle_exception thrown
line 63 of /blocks/backmeup/portfoliofile.php: call to error()
line 50 of /blocks/backmeup/portfoliofile.php: call to not_found()
Output buffer: /data/www/gtndevel/moodledata/bmu/temp/exportdata/backmeup_2012_10_30_16_07/Game Based Learning/Aufteilung der Begriffe für das Glossar.html
```

The following error occurred aswell:

```
org.jdom2.input.JDOMParseException: Error on line 2 of document http://gtn02.gtn-solutions.com/moodle20/blocks/backmeup/service.php?username=backmeup&password=286bafbb1a9faf4dc4e104a33e222304&action=list: Content is not allowed in prolog.
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:228)
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:329)
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1256)
        at org.backmeup.moodle.MoodleDatasource.list(MoodleDatasource.java:63)
        at org.backmeup.plugin.api.connectors.FilesystemLikeDatasource.list(FilesystemLikeDatasource.java:51)
        at org.backmeup.plugin.api.connectors.FilesystemLikeDatasource.downloadAll(FilesystemLikeDatasource.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:228)
        at $Proxy98.downloadAll(Unknown Source)
        at org.backmeup.job.impl.BackupJobRunner.executeBackup(BackupJobRunner.java:187)
        at org.backmeup.job.impl.rabbitmq.RabbitMQJobReceiver$1.run(RabbitMQJobReceiver.java:141)
        at java.lang.Thread.run(Thread.java:679)
Caused by: org.xml.sax.SAXParseException; systemId: http://gtn02.gtn-solutions.com/moodle20/blocks/backmeup/service.php?username=backmeup&password=286bafbb1a9faf4dc4e104a33e222304&action=list; lineNumber: 2; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:391)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1404)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:625)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:488)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:819)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:748)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1208)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:525)
        at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
        ... 14 more
```

I guess the network connection to the moodle server crashes / drops at some point; or the moodle server cannot handle that much requests anymore.

**Comment by fjungwirth** [comment]
The server-side moodle plugin now creats for each request an unique backup-folder so there should not be any overlaps anymore.
Folder is now username_timestamp + ongoing id, if there are more than one request per secend per user

**Comment by ghost** [comment]
tested by running 10 threads each queuing 10 jobs (total 100 jobs) => exception described above didn't occur anymore!
