### ISSUE TITLE
Index-Action fails with an ActionException (BackupJobRunner)

### ISSUE THREAD

**Issue by ghost** [backmeup/backmeup-prototype#73]
I've just ran one Moodle-to-Zip-Job which resulted in following error during the execution of the Indexer:

```
Pusing to ES index...org.backmeup.plugin.api.actions.ActionException: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [modified]
        at org.backmeup.plugin.api.actions.indexing.IndexAction.doAction(IndexAction.java:55)
        at org.backmeup.job.impl.BackupJobRunner.executeBackup(BackupJobRunner.java:232)
        at org.backmeup.job.impl.rabbitmq.RabbitMQJobReceiver$1.run(RabbitMQJobReceiver.java:141)
        at java.lang.Thread.run(Thread.java:679)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [modified]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:327)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:598)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:494)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:438)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:288)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:210)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        ... 1 more
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [31.07.2011 00:24:24 CEST], tried both date format [dateOptionalTime], and timestamp number
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:428)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:357)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:181)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:314)
        ... 11 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "31.07.2011 00:24:24 CEST" is malformed at ".07.2011 00:24:24 CEST"
        at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:747)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:422)
        ... 14 more
org.backmeup.plugin.api.actions.ActionException: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [modified]
        at org.backmeup.plugin.api.actions.indexing.IndexAction.doAction(IndexAction.java:55)
        at org.backmeup.job.impl.BackupJobRunner.executeBackup(BackupJobRunner.java:232)
        at org.backmeup.job.impl.rabbitmq.RabbitMQJobReceiver$1.run(RabbitMQJobReceiver.java:141)
        at java.lang.Thread.run(Thread.java:679)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse [modified]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:327)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:598)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:494)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:438)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:288)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:210)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:430)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        ... 1 more
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [31.07.2011 00:24:24 CEST], tried both date format [dateOptionalTime], and timestamp number
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:428)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:357)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:181)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:314)
        ... 11 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "31.07.2011 00:24:24 CEST" is malformed at ".07.2011 00:24:24 CEST"
        at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:747)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:422)
        ... 14 more
```

Despite this error, the job finishes as expected (ZIP file gets created and job finishes successfully).
You might reproduce this by running following command on bmu2:

```
root@bmu-dev02:/data/backmeup-prototype/python-tests# python ParallelJobsMoodleZip.py -j 1 -c 1
```

**Comment by rsimon** [comment]
Hm... the cause is that the Indexer automatically recognizes the contents of the Moodle Plugin 'modified' field as date, but then is unable to parse it because it's not valid ISO format. Standard way to output "31.07.2011 00:24:24 CEST" would be

2012-07-31T00:24:24.962Z

**Comment by fjungwirth** [comment]
The Moodle Plugin now provides the modified field as an ISO 8601 date and looks like this: 2004-02-12T15:19:21+00:00

**Comment by rsimon** [comment]
Ok - tested again and can confirm the exception is gone! Querying the index with

http://bmu-dev02.x:9200/_search?q=*:*Panorama*&pretty=true

Returned the image http://commons.wikimedia.org/wiki/File:Panorama_altmuehltal6.jpg, from "Backmeup Kurs #1", so this seems to work allright now.
