### ISSUE TITLE
plugins not working on server

### ISSUE THREAD

**Issue by fetzig** [backmeup/backmeup-prototype#98]
newly created dropbox, facebook, twitter datasouce profiles don't work. dropbox event throws an error when requesting the datasource profile options.

**Comment by ghost** [comment]
I've just created new dropbox and facebook jobs on dev01, using new profiles for dropbox and facebook. Both jobs work as expected.
To fix your problems, please 

Additionally I tested the profile options:

```
POST http://127.0.0.1:8080/datasources/ptest@trash-mail.com/profiles/136/options keyRing=123456789

{
  "sourceOptions": [
    "/BMU_mail_37_19_11_2012_15_38",
    "/BMU_mail_100_20_11_2012_11_27",
    "/BMU_mail_103_20_11_2012_11_38",
    "/BMU_skydrive_1_29_10_2012_15_38",
    "/BMU_twitter_2_05_11_2012_11_23",
    "/Getting%20Started.pdf",
    "/html.txt",
    "/Photos",
    "/plain.txt",
    "/Public"
  ]
}
```

Seems to be working as expected! 

I guess that the authentication data of your profiles are invalid, cause I've found some information about that in the log file:

```
12/11/23 16:45:36 ERROR impl.BusinessLogicImpl: Error during getAvailableOptions
org.backmeup.model.exceptions.PluginException: An exception occured during execution of the method getAvailableOptions
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:229)
        at $Proxy90.getAvailableOptions(Unknown Source)
        at org.backmeup.logic.impl.BusinessLogicImpl.getDatasourceOptions(BusinessLogicImpl.java:458)
        at org.backmeup.logic.impl.BusinessLogicImpl$Proxy$_$$_WeldClientProxy.getDatasourceOptions(BusinessLogicImpl$Proxy$_$$_WeldClientProxy.java)
        at org.backmeup.rest.Datasources.getDatasourceOptions(Datasources.java:110)
        at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222)
        at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211)
        at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:119)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:208)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)
        at org.jboss.resteasy.plugins.server.tjws.TJWSServletDispatcher.service(TJWSServletDispatcher.java:40)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:50)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2326)
        at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2280)
        at Acme.Serve.Serve$ServeConnection.run(Serve.java:2052)
        at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1402)
        at java.lang.Thread.run(Thread.java:679)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor218.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.backmeup.plugin.osgi.PluginImpl$1.invoke(PluginImpl.java:227)
        ... 24 more
Caused by: org.backmeup.model.exceptions.PluginException: Failed to determine root folders
        at org.backmeup.dropbox.DropboxDatasource.getAvailableOptions(DropboxDatasource.java:126)
        ... 28 more
Caused by: com.dropbox.client2.exception.DropboxUnlinkedException
        at com.dropbox.client2.RESTUtility.parseAsJSON(Unknown Source)
        at com.dropbox.client2.RESTUtility.execute(Unknown Source)
        at com.dropbox.client2.RESTUtility.execute(Unknown Source)
        at com.dropbox.client2.RESTUtility.streamRequest(Unknown Source)
        at com.dropbox.client2.RESTUtility.request(Unknown Source)
        at com.dropbox.client2.DropboxAPI.metadata(Unknown Source)
        at org.backmeup.dropbox.DropboxDatasource.getAvailableOptions(DropboxDatasource.java:120)
        ... 28 more

```

**Comment by fetzig** [comment]
was a frontend bug. is fixed now, and works on the server. sorry for the noise.
